#!/bin/bash

# Prepares your system to run Athena
clear
if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root if you want to"
	echo "install Perl Modules or set up the Apache Web Server"
	echo "OK to continue Y/n"
	read -s -n 1 ans
	if [ "$ans" = "" ]; then
		ans=y
	fi
	if [ "$ans" != "y" ]; then
		echo "Quitting"
		exit 1
	fi 
fi

platform='unknown'
if [ -f /etc/redhat-release ]; then
platform='redhat'
elif [ -f /etc/debian_version ]; then
platform='debian'
elif [ -f /etc/SUSE-brand ]; then
platform='suse'
fi

spacer="---------------------------------------------------------------"
installPromt="Would you like me to install it now? Y/n:"
echo $spacer
echo "Setting up phpStartPoint to create PHP classes and web interfaces ... "
echo $spacer
echo "Checking your OS and environment"
echo OS is $platform based

if [[ $platform == 'suse' ]]; then

	echo $spacer
	echo "Install any missing stuff? Y/n:"	
	read -s -n 1 ans
	if [ "$ans" = "" ]; then 
		ans=y
	fi 	
	if [ "$ans" = "y" ]; then 
				
		zypper install mariadb
		systemctl start mariadb
		systemctl enable mariadb
		aptitude -y install php5 php5-mysql apache2 apache2-mod_php5 perl-DBI perl-Term-ReadKey perl-DBD-mysql
		rcmysql start
		rcapache2 start
	fi				    
fi


if [[ $platform == 'debian' ]]; then

	echo $spacer
	echo "Check for software to be installed, e.g. Apache2, php5, MySQL and some extra php and perl modules"	
	echo $installPromt	
	read -s -n 1 ans
	if [ "$ans" = "" ]; then 
		ans=y
	fi 	
    if [ "$ans" = "y" ]; then 
			    
		if [ "$(id -u)" != "0" ]; then
		   echo "This script must be run as root" 1>&2
		   exit 1
		fi
		apt-get -y install libterm-readkey-perl libdbi-perl apache2 mysql-server php5 php5-cli libapache2-mod-php5 expect libcrypt-ssleay-perl libexpect-perl php5-mysqlnd php5-mcrypt libtest-www-mechanize-perl liblocale-currency-format-perl libpdf-create-perl libcrypt-cbc-perl libdatetime-perl
	else
		echo "Ok ... skipping"
	fi
fi

if [[ $platform == 'redhat' ]]; then


	echo $spacer
	echo "Install any missing stuff? Y/n:"	
	read -s -n 1 ans
	if [ "$ans" = "" ]; then 
		ans=y
	fi 	
	if [ "$ans" = "y" ]; then 	
		if [ "$(id -u)" != "0" ]; then
		   echo "This script must be run as root" 1>&2
		   exit 1
		fi
		
		yum install httpd perl-DBI perl-TermReadKey perl-DBD-mysql mariadb-server php php-mysql perl-WWW-Mechanize
		service httpd start
		systemctl start mariadb
		systemctl enable mariadb
		
		chkconfig httpd on
		chkconfig mysqld on
		service httpd restart
	fi
fi

echo
echo $spacer
echo -n "OK, step 2, going to grab the setup script from the web "
echo "and continue the installation... "
echo "Type 'd' for the Development version"
echo "Type 'c' to cancel:"
echo $spacer
read -n 1 resp

if [ "$resp" = "d" ]; then
	wget -N https://raw.githubusercontent.com/athenasystems/athena/master/athena-dev-install
	chmod 755 athena-dev-install
	perl ./athena-dev-install
	rm athena-dev-install
else
	echo "Quiting"
fi

exit 1

